LEXICON_RU = {
    "start_greeting": "Салют, {user_name}! 👋\n\nЯ твой личный ассистент. Как будем двигаться дальше? Можешь записаться сам или пообщаться с моим нейросетевым бро.",
    "button_manual": "📝 Запись / К владельцу",
    "button_ai": "🤖 Общаться с ИИ",
    "manual_response": "Окей, бро! Вот ссылка на запись или контакт владельца: @owner_handle. Действуй! 🚀",
    "ai_response": "ИИ-бро на связи! 🧠 Задавай любой вопрос по стрижкам или сервису, он в курсе всех дел.",
    "ai_button_pressed": "Запускаю нейронку...",
    "manual_button_pressed": "Открываю контакты...",
    "button_book": "🗓 Записаться",
    "manual_menu_text": "Выбирай, что нужно сделать:",
    "book_appointment_text": "Выбери месяц для записи:",
    "month_january": "Январь",
    "month_february": "Февраль",
    "month_march": "Март",
    "month_april": "Апрель",
    "month_may": "Май",
    "month_june": "Июнь",
    "month_july": "Июль",
    "month_august": "Август",
    "month_september": "Сентябрь",
    "month_october": "Октябрь",
    "month_november": "Ноябрь",
    "month_december": "Декабрь",
    "button_back_to_manual_menu": "⬅️ Назад в меню записи",
    "month_selected_text": "Выбери день в {month_name} {year}:",
    "button_prev_month": "◀️",
    "button_next_month": "▶️",
    "button_cancel_booking": "Отмена записи",
    "weekday_mon": "Пн",
    "weekday_tue": "Вт",
    "weekday_wed": "Ср",
    "weekday_thu": "Чт",
    "weekday_fri": "Пт",
    "weekday_sat": "Сб",
    "weekday_sun": "Вс",
    "booking_cancelled": "Запись отменена. Возвращаюсь в главное меню.",
    "day_selected_text": "Чётко! Дата выбрана: <b>{date}</b>. Теперь определимся со временем:",
    "confirm_booking_text": "Записываемся на <b>{date}</b> в <b>{time}</b>?\n\nЖми на галку, если всё чётко!",
    "booking_confirmed": "Записал тебя, бро! До встречи ✊",
    "booking_success": "✅ Запись успешно создана! Ждем тебя.",
    "booking_error": "❌ Ошибка бэкенда. Попробуй позже или напиши владельцу.",
    "button_confirm": "✅ Подтвердить",
    "button_cancel": "❌ Отмена",
    "button_back_to_days": "⬅️ К выбору даты",
    "date_format": "{day:02d}.{month:02d}.{year}",
    "log_bot_starting": "Запуск бота...",
    "log_bot_started": "Бот успешно запущен и готов к стрижкам!",
}